Repository jenkinsci/jellydoc-maven-plugin, pull requests merged in 2023-07, with the labels that each got.

#50 Fix GH ribbon on site by updating maven-fluido-skin and keeping track of it
  .github/renovate.json
  maven-jellydoc-plugin/src/site/site.xml
Labels: chore

#52 Rebrand as 'jellydoc-maven-plugin'
  .github/renovate.json
  .github/workflows/site.yml
  annotation/pom.xml
  jellydoc-maven-plugin/pom.xml
  jellydoc-maven-plugin/schemagen-on-jelly.sh
  jellydoc-maven-plugin/schemas/ant.xsd
  jellydoc-maven-plugin/schemas/antlr.xsd
  jellydoc-maven-plugin/schemas/bean.xsd
  jellydoc-maven-plugin/schemas/beanshell.xsd
  jellydoc-maven-plugin/schemas/betwixt.xsd
  jellydoc-maven-plugin/schemas/bsf.xsd
  jellydoc-maven-plugin/schemas/core.xsd
  jellydoc-maven-plugin/schemas/define.xsd
  jellydoc-maven-plugin/schemas/dynabean.xsd
  jellydoc-maven-plugin/schemas/email.xsd
  jellydoc-maven-plugin/schemas/fmt.xsd
  jellydoc-maven-plugin/schemas/html.xsd
  jellydoc-maven-plugin/schemas/http.xsd
  jellydoc-maven-plugin/schemas/interaction.xsd
  jellydoc-maven-plugin/schemas/jaxme.xsd
  jellydoc-maven-plugin/schemas/jetty.xsd
  jellydoc-maven-plugin/schemas/jface.xsd
  jellydoc-maven-plugin/schemas/jms.xsd
  jellydoc-maven-plugin/schemas/jmx.xsd
  jellydoc-maven-plugin/schemas/jsl.xsd
  jellydoc-maven-plugin/schemas/junit.xsd
  jellydoc-maven-plugin/schemas/log.xsd
  jellydoc-maven-plugin/schemas/memory.xsd
  jellydoc-maven-plugin/schemas/ojb.xsd
  jellydoc-maven-plugin/schemas/quartz.xsd
  jellydoc-maven-plugin/schemas/regexp.xsd
  jellydoc-maven-plugin/schemas/soap.xsd
  jellydoc-maven-plugin/schemas/sql.xsd
  jellydoc-maven-plugin/schemas/swing.xsd
  jellydoc-maven-plugin/schemas/swt.xsd
  jellydoc-maven-plugin/schemas/threads.xsd
  jellydoc-maven-plugin/schemas/util.xsd
  jellydoc-maven-plugin/schemas/validate.xsd
  jellydoc-maven-plugin/schemas/velocity.xsd
  jellydoc-maven-plugin/schemas/xml.xsd
  jellydoc-maven-plugin/schemas/xmlunit.xsd
  jellydoc-maven-plugin/src/main/java/org/jvnet/maven/jellydoc/JellydocMojo.java
  jellydoc-maven-plugin/src/main/java/org/jvnet/maven/jellydoc/ReferenceRenderer.java
  jellydoc-maven-plugin/src/main/java/org/jvnet/maven/jellydoc/TagXMLDoclet.java
  jellydoc-maven-plugin/src/main/resources/org/jvnet/maven/jellydoc/xsdgen.xsl
  jellydoc-maven-plugin/src/site/apt/index.apt
  jellydoc-maven-plugin/src/site/site.xml
  jellydoc-maven-plugin/src/test/java/org/jvnet/maven/jellydoc/Junit4TestsRanTest.java
  pom.xml
  taglib-xml-writer/pom.xml
Labels: breaking

#53 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  annotation/pom.xml
  jellydoc-maven-plugin/pom.xml
  pom.xml
  taglib-xml-writer/pom.xml
Labels: developer

#54 Use non-reusable CD workflow
  .github/workflows/cd.yaml
Labels: chore

#57 Downgrade incrementals tooling to last version that supports Java 8
  .github/dependabot.yml
  .mvn/extensions.xml
Labels: skip-changelog

#59 Rename 'annotation' to 'jellydoc-annotations'
  jellydoc-annotations/pom.xml
  jellydoc-annotations/schemagen-on-jelly.sh
  jellydoc-annotations/schemas/ant.xsd
  jellydoc-annotations/schemas/antlr.xsd
  jellydoc-annotations/schemas/bean.xsd
  jellydoc-annotations/schemas/beanshell.xsd
  jellydoc-annotations/schemas/betwixt.xsd
  jellydoc-annotations/schemas/bsf.xsd
  jellydoc-annotations/schemas/core.xsd
  jellydoc-annotations/schemas/define.xsd
  jellydoc-annotations/schemas/dynabean.xsd
  jellydoc-annotations/schemas/email.xsd
  jellydoc-annotations/schemas/fmt.xsd
  jellydoc-annotations/schemas/html.xsd
  jellydoc-annotations/schemas/http.xsd
  jellydoc-annotations/schemas/interaction.xsd
  jellydoc-annotations/schemas/jaxme.xsd
  jellydoc-annotations/schemas/jetty.xsd
  jellydoc-annotations/schemas/jface.xsd
  jellydoc-annotations/schemas/jms.xsd
  jellydoc-annotations/schemas/jmx.xsd
  jellydoc-annotations/schemas/jsl.xsd
  jellydoc-annotations/schemas/junit.xsd
  jellydoc-annotations/schemas/log.xsd
  jellydoc-annotations/schemas/memory.xsd
  jellydoc-annotations/schemas/ojb.xsd
  jellydoc-annotations/schemas/quartz.xsd
  jellydoc-annotations/schemas/regexp.xsd
  jellydoc-annotations/schemas/soap.xsd
  jellydoc-annotations/schemas/sql.xsd
  jellydoc-annotations/schemas/swing.xsd
  jellydoc-annotations/schemas/swt.xsd
  jellydoc-annotations/schemas/threads.xsd
  jellydoc-annotations/schemas/util.xsd
  jellydoc-annotations/schemas/validate.xsd
  jellydoc-annotations/schemas/velocity.xsd
  jellydoc-annotations/schemas/xml.xsd
  jellydoc-annotations/schemas/xmlunit.xsd
  jellydoc-annotations/src/main/java/org/jvnet/maven/jellydoc/annotation/NoContent.java
  jellydoc-annotations/src/main/java/org/jvnet/maven/jellydoc/annotation/Required.java
  jellydoc-annotations/src/main/java/org/jvnet/maven/jellydoc/annotation/TagLibUri.java
  pom.xml
Labels: chore

#61 Update jaxen from 1.2.0 to 2.0.0
  .github/dependabot.yml
  jellydoc-maven-plugin/pom.xml
Labels: dependencies

#62 Update nekohtml from 1.9.6.2 to 1.9.22
  jellydoc-maven-plugin/pom.xml
Labels: dependencies

#60 Require Java 11 or newer
  .github/dependabot.yml
  .github/workflows/cd.yaml
  .github/workflows/site.yml
  .mvn/extensions.xml
  Jenkinsfile
  jellydoc-maven-plugin/pom.xml
  jellydoc-maven-plugin/src/main/java/org/jvnet/maven/jellydoc/JellydocMojo.java
  jellydoc-maven-plugin/src/main/java/org/jvnet/maven/jellydoc/TagXMLDoclet.java
  pom.xml
Labels: internal
